# Generated by Django 5.2.4 on 2025-08-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_auto_reply_project', '0002_inquiryquestion_answer_inquiryquestion_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiryquestion',
            name='question',
            field=models.TextField(),
        ),
    ]
