# Generated by Django 5.2.4 on 2025-08-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_auto_reply_project', '0003_alter_inquiryquestion_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiryuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='inquiryuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='inquiryuser',
            name='name',
            field=models.CharField(default='guest user', max_length=200),
        ),
    ]
